export const skillsLocals = [
    { label: "javascript", value: "javascript" },
  { label: "python", value: "python" },
  { label: "java", value: "java" },
  { label: "csharp", value: "csharp" },
  { label: "php", value: "php" },
  { label: "mysql", value: "mysql" },
  { label: "mongodb", value: "mongodb" },
  { label: "postgresql", value: "postgresql" },
  { label: "html", value: "html" },
  { label: "css", value: "css" },
  { label: "react", value: "react" },
  { label: "angular", value: "angular" },
  { label: "vue", value: "vue" },
  { label: "docker", value: "docker" },
  { label: "kubernetes", value: "kubernetes" },
  { label: "aws", value: "aws" },
  { label: "azure", value: "azure" },
  { label: "flutter", value: "flutter" },
  { label: "swift", value: "swift" },
  { label: "kotlin", value: "kotlin" },
  { label: "excel", value: "excel" },
  { label: "sql", value: "sql" },
  { label: "r", value: "r" },
  { label: "figma", value: "figma" },
  { label: "photoshop", value: "photoshop" },
  { label: "illustrator", value: "illustrator" },
  { label: "seo", value: "seo" },
  { label: "storytelling", value: "storytelling" },
  { label: "ux", value: "ux" },
  { label: "ui", value: "ui" },
  { label: "scrum", value: "scrum" },
  { label: "agile", value: "agile" },
  { label: "kanban", value: "kanban" },
  { label: "publicspeaking", value: "publicspeaking" },
  { label: "writing", value: "writing" },
  { label: "networking", value: "networking" },
  { label: "english", value: "english" },
  { label: "spanish", value: "spanish" },
  { label: "german", value: "german" },
  { label: "chinese", value: "chinese" },
  { label: "french", value: "french" },
  { label: "office", value: "office" },
  { label: "trello", value: "trello" },
  { label: "notion", value: "notion" },
  { label: "salesforce", value: "salesforce" },
]

export const domainesActivites = [
  { label: "technologie", value: "technologie" },
  { label: "finance", value: "finance" },
  { label: "santé", value: "santé" },
  { label: "éducation", value: "éducation" },
  { label: "commerce de détail", value: "commerce de détail" },
  { label: "industrie", value: "industrie" },
  { label: "construction", value: "construction" },
  { label: "immobilier", value: "immobilier" },
  { label: "transport", value: "transport" },
  { label: "hôtellerie", value: "hôtellerie" },
  { label: "divertissement", value: "divertissement" },
  { label: "médias", value: "médias" },
  { label: "télécommunications", value: "télécommunications" },
  { label: "énergie", value: "énergie" },
  { label: "agriculture", value: "agriculture" },
  { label: "services juridiques", value: "services juridiques" },
  { label: "conseil", value: "conseil" },
  { label: "organisation à but non lucratif", value: "organisation à but non lucratif" },
  { label: "gouvernement", value: "gouvernement" },
  { label: "marketing", value: "marketing" },
  { label: "publicité", value: "publicité" },
  { label: "alimentation et boissons", value: "alimentation et boissons" },
  { label: "art et design", value: "art et design" },
  { label: "sport", value: "sport" },
  { label: "e-commerce", value: "e-commerce" },
  { label: "cybersécurité", value: "cybersécurité" },
];

export const contractType = [
  { label: "CDI", value: "CDI" },
  { label: "CDD", value: "CDD" },
  { label: "Stage", value: "Stage" },
  { label: "Freelance", value: "Freelance" },
  { label: "Sous-traitance", value: "Sous-traitance" },
]
