export const skillsLocals = [
    { label: "javascript", value: "javascript" },
  { label: "python", value: "python" },
  { label: "java", value: "java" },
  { label: "csharp", value: "csharp" },
  { label: "php", value: "php" },
  { label: "mysql", value: "mysql" },
  { label: "mongodb", value: "mongodb" },
  { label: "postgresql", value: "postgresql" },
  { label: "html", value: "html" },
  { label: "css", value: "css" },
  { label: "react", value: "react" },
  { label: "angular", value: "angular" },
  { label: "vue", value: "vue" },
  { label: "docker", value: "docker" },
  { label: "kubernetes", value: "kubernetes" },
  { label: "aws", value: "aws" },
  { label: "azure", value: "azure" },
  { label: "flutter", value: "flutter" },
  { label: "swift", value: "swift" },
  { label: "kotlin", value: "kotlin" },
  { label: "excel", value: "excel" },
  { label: "sql", value: "sql" },
  { label: "r", value: "r" },
  { label: "figma", value: "figma" },
  { label: "photoshop", value: "photoshop" },
  { label: "illustrator", value: "illustrator" },
  { label: "seo", value: "seo" },
  { label: "storytelling", value: "storytelling" },
  { label: "ux", value: "ux" },
  { label: "ui", value: "ui" },
  { label: "scrum", value: "scrum" },
  { label: "agile", value: "agile" },
  { label: "kanban", value: "kanban" },
  { label: "publicspeaking", value: "publicspeaking" },
  { label: "writing", value: "writing" },
  { label: "networking", value: "networking" },
  { label: "english", value: "english" },
  { label: "spanish", value: "spanish" },
  { label: "german", value: "german" },
  { label: "chinese", value: "chinese" },
  { label: "french", value: "french" },
  { label: "office", value: "office" },
  { label: "trello", value: "trello" },
  { label: "notion", value: "notion" },
  { label: "salesforce", value: "salesforce" },
]

export const domainesActivites = [
  { label: "Technologie", value: "Technologie" },
  { label: "finance", value: "finance" },
  { label: "santé", value: "santé" },
  { label: "éducation", value: "éducation" },
  { label: "commerce de détail", value: "commerce de détail" },
  { label: "industrie", value: "industrie" },
  { label: "construction", value: "construction" },
  { label: "immobilier", value: "immobilier" },
  { label: "transport", value: "transport" },
  { label: "hôtellerie", value: "hôtellerie" },
  { label: "divertissement", value: "divertissement" },
  { label: "médias", value: "médias" },
  { label: "télécommunications", value: "télécommunications" },
  { label: "énergie", value: "énergie" },
  { label: "agriculture", value: "agriculture" },
  { label: "services juridiques", value: "services juridiques" },
  { label: "conseil", value: "conseil" },
  { label: "organisation à but non lucratif", value: "organisation à but non lucratif" },
  { label: "gouvernement", value: "gouvernement" },
  { label: "marketing", value: "marketing" },
  { label: "publicité", value: "publicité" },
  { label: "alimentation et boissons", value: "alimentation et boissons" },
  { label: "art et design", value: "art et design" },
  { label: "sport", value: "sport" },
  { label: "e-commerce", value: "e-commerce" },
  { label: "cybersécurité", value: "cybersécurité" },
];

export const contractType = [
  { label: "CDI", value: "CDI" },
  { label: "CDD", value: "CDD" },
  { label: "Intérim", value: "Intérim" },
  { label: "Stage", value: "Stage" },
]

export const degreeAccademy = [
  { label: "CEPE", value: "CEPE:0" },
  { label: "BEPC", value: "BEPC:1" },
  { label: "BAC", value: "BAC:2" },
  { label: "BAC+1", value: "BAC+1:3" },
  { label: "BAC+2", value: "BAC+2:4" },
  { label: "BAC+3", value: "BAC+3:5" },
  { label: "BAC+4", value: "BAC+4:6" },
  { label: "BAC+5", value: "BAC+5:7" },
  { label: "BAC+6", value: "BAC+6:8" },
  { label: "DOCTORAT", value: "DOCTORAT:9" },
]

export const certificationsLocal = [
  { label: "Certified Scrum Master (CSM)", value: "Certified Scrum Master (CSM)" },
  { label: "Project Management Professional (PMP)", value: "Project Management Professional (PMP)" },
  { label: "Cisco Certified Network Associate (CCNA)", value: "Cisco Certified Network Associate (CCNA)" },
  { label: "AWS Certified Solutions Architect", value: "AWS Certified Solutions Architect" },
  { label: "Microsoft Certified: Azure Fundamentals", value: "Microsoft Certified: Azure Fundamentals" },
  { label: "Google Data Analytics Professional Certificate", value: "Google Data Analytics Professional Certificate" },
  { label: "CompTIA Security+", value: "CompTIA Security+" },
  { label: "Certified Ethical Hacker (CEH)", value: "Certified Ethical Hacker (CEH)" },
  { label: "ITIL Foundation Certification", value: "ITIL Foundation Certification" },
  { label: "SAP Certified Application Associate", value: "SAP Certified Application Associate" },
  { label: "Adobe Certified Expert (ACE)", value: "Adobe Certified Expert (ACE)" },
  { label: "Chartered Financial Analyst (CFA)", value: "Chartered Financial Analyst (CFA)" },
  { label: "Google Ads Certification", value: "Google Ads Certification" },
  { label: "Six Sigma Green Belt Certification", value: "Six Sigma Green Belt Certification" },
  { label: "CISSP - Certified Information Systems Security Professional", value: "CISSP - Certified Information Systems Security Professional" },
  { label: "Certified Public Accountant (CPA)", value: "Certified Public Accountant (CPA)" },
  { label: "Hootsuite Social Marketing Certification", value: "Hootsuite Social Marketing Certification" },
  { label: "TOEFL Certification", value: "TOEFL Certification" },
  { label: "IELTS Certification", value: "IELTS Certification" },
  { label: "AutoDesk Certified Professional", value: "AutoDesk Certified Professional" },
];


